stages:
- start
- test

start:
  image: docker/compose
  stage: start
  services:
    - docker:dind

  script:
  - docker-compose -f docker-compose.ci.yml -f docker-compose.yml up -d

test:
  stage: test
  image: docker/compose
  services:
    - docker:dind

  script:
  - docker-compose -f docker-compose.ci.yml -f docker-compose.yml up ci

