image: ubuntu
stages:
  - build

build:
  stage: build
  script:
    - docker build -t comp.se.140-imed /IMED
    - docker build -t comp.se.140-orig /ORIG
    - docker build -t comp.se.140-obse /OBSE
    - docker build -t comp.se.140-httpserv /HTTPSERV

