stages:
  - build

services:
- docker:dind

before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
- echo $CI_REGISTRY
- echo $CI_REGISTRY_USER
- echo $CI_REGISTRY_PASSWORD


build:
  stage: build
  image: docker:latest
  script:
    - docker build -t registry.gitlab.com/juubes/comp.se.140 ./IMED
    - docker build -t registry.gitlab.com/juubes/comp.se.140 ./ORIG
    - docker build -t registry.gitlab.com/juubes/comp.se.140 ./OBSE
    - docker build -t registry.gitlab.com/juubes/comp.se.140 ./HTTPSERV

    - docker push registry.gitlab.com/juubes/comp.se.140
    - docker push registry.gitlab.com/juubes/comp.se.140
    - docker push registry.gitlab.com/juubes/comp.se.140
    - docker push registry.gitlab.com/juubes/comp.se.140
