stages:
  - build

services:
- docker:dind

before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
- echo $CI_REGISTRY
- echo $CI_REGISTRY_USER
- echo $CI_REGISTRY_PASSWORD


build:
  stage: build
  image: docker:latest
  script:
    - docker build -t registry.gitlab.com/juubes/comp.se.140/imed ./IMED
    - docker build -t registry.gitlab.com/juubes/comp.se.140/orig ./ORIG
    - docker build -t registry.gitlab.com/juubes/comp.se.140/obse ./OBSE
    - docker build -t registry.gitlab.com/juubes/comp.se.140/httpserv ./HTTPSERV

    - docker push registry.gitlab.com/juubes/comp.se.140/imed
    - docker push registry.gitlab.com/juubes/comp.se.140/orig
    - docker push registry.gitlab.com/juubes/comp.se.140/obse
    - docker push registry.gitlab.com/juubes/comp.se.140/httpserv

test:
  stage: test
  image: ubuntu:latest
  services:
    - registry.gitlab.com/juubes/comp.se.140/imed
    - registry.gitlab.com/juubes/comp.se.140/orig
    - registry.gitlab.com/juubes/comp.se.140/obse
    - registry.gitlab.com/juubes/comp.se.140/httpserv

  script:
    - curl http://httpserv:8080/