version: "3.1"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    networks:
      - system

  GATEWAY:
    image: gateway
    build:
      context: ./API-GATEWAY
    ports:
      - 8083:8083
    networks:
      - system

  HTTPSERV:
    image: httpserv
    build:
      context: ./HTTPSERV
    networks:
      - system

  IMED:
    image: imed
    build:
      context: ./IMED
    networks:
      - system

  OBSE:
    image: obse
    hostname: obse
    build:
      context: ./OBSE
    volumes:
      - /app/volume
    networks:
      - system

  ORIG:
    image: orig
    build:
      context: ./ORIG
    networks:
      - system

networks:
  system:
    internal: true
