version: "3.1"
services:
  CI:
    image: ci
    hostname: ci
    build:
      context: ./CI-TESTS

    depends_on:
      - rabbitmq
      - HTTPSERV
      - GATEWAY
      - IMED
      - OBSE
      - ORIG

    networks:
      - system
