version: "3.1"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  GATEWAY:
    image: gateway
    build:
      context: ./API-GATEWAY
    ports:
      - 8083:8083

  HTTPSERV:
    image: httpserv
    build:
      context: ./HTTPSERV

  IMED:
    image: imed
    build:
      context: ./IMED

  OBSE:
    image: obse
    hostname: obse
    build:
      context: ./OBSE

  ORIG:
    image: orig
    build:
      context: ./ORIG
