services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672

  HTTPSERV:
    image: httpserv
    build:
      context: ./HTTPSERV
    ports:
      - 8080:8080

  IMED:
    image: imed
    build:
      context: ./IMED

  OBSE:
    image: obse
    hostname: obse
    build:
      context: ./OBSE

  ORIG:
    image: orig
    build:
      context: ./ORIG
